### ISSUE TITLE
정상 작동 안 됨 문제.

### ISSUE THREAD

**Issue by sjkel** [jubin-park/rgss#1]
제대로 작동 하지 않습니다. 스크립트 8번 해야 겨우 될 정도 이나, 인식되더라도 로컬로 됩니다. 시간 주소 추천 및 직접 테스트 후 해결 되면 다시 올려주시거나, 카톡디: ab2601 부탁드려요.

**Comment by sjkel** [comment]
webtime 문제 입니다.

**Comment by jubin-park** [comment]
답변이 늦어 죄송합니다.

WebTime이 인터넷 시간을 파싱하는 과정에서 문자열 데이터가 손실이 되는 것을 확인했습니다.
가령 "20/02/25 오후 11:38:42"라는 문자열을 받아올 때, "2/2/25 오후 11:38:42" 로 받아옵니다. 따라서 날짜가 2002년으로 설정되어 정상적인 시간을 받아오지 못합니다.

수정 후 답변 드리겠습니다. 감사합니다.

**Comment by jubin-park** [comment]
답변이 늦어 죄송합니다.

WebTime이 인터넷 시간을 파싱하는 과정에서 문자열 데이터가 손실이 되는 것을 확인했습니다.
원인은 유니코드로 인코딩할 때 숫자 0이 제거되는 버그였습니다.
가령 "20/02/25 오후 11:38:42"라는 문자열을 받아올 때, "2/2/25 오후 11:38:42" 로 받아옵니다. 따라서 날짜가 2002년으로 설정되어 정상적인 시간을 받아오지 못합니다.

수정하였으니 스크립트를 새로 받아주세요. 감사합니다.
